# Generated by Django 6.0.2 on 2026-03-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("product_type", models.CharField(max_length=100)),
                ("frame", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=50)),
                ("photo", models.ImageField(upload_to="orders/")),
                ("note", models.TextField(blank=True)),
            ],
        ),
    ]
