# Generated by Django 6.0.2 on 2026-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("state", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
