# Generated by Django 6.0.2 on 2026-03-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0002_register"),
    ]

    operations = [
        migrations.RenameField(
            model_name="register",
            old_name="state",
            new_name="address",
        ),
    ]
