# Generated by Django 6.0.2 on 2026-03-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basics", "0003_rename_state_register_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="photo",
        ),
        migrations.AddField(
            model_name="order",
            name="keychain",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="photo1",
            field=models.ImageField(blank=True, null=True, upload_to="orders/"),
        ),
        migrations.AddField(
            model_name="order",
            name="photo2",
            field=models.ImageField(blank=True, null=True, upload_to="orders/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="frame",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
